### ISSUE TITLE
Figure out how to modernize the app

### ISSUE THREAD

**Issue by natewhit44** [natewhit44/Recipe-Repository-App#2]
This app should be mainly fixed position, with an overflow property for the work space. We should spend some time crafting the CSS to make the side look bubbly and attractive.

**Comment by mckencod** [comment]
Here are some links to explain about modernizing:
https://www.smashingmagazine.com/user-interface-design-in-modern-web-applications/

https://msdn.microsoft.com/en-us/library/windows/apps/jj839734.aspx

https://designmodo.com/web-application-interface/

https://www.zebra.com/us/en/cpn/os-migration/modernize-your-apps.html?tactic_type=SEMG&tactic_detail=OS+-+Modernize+Your+Apps_IT_NA_None_Software

http://vasiligfx.deviantart.com/art/Video-System-Web-Design-342904540
